[agent]
  debug = true
  interval = "10s"
  flush_interval = "10s"
  metric_batch_size = 1000
  metric_buffer_limit = 50000

[[inputs.netflow]]
  service_address = "udp://:2055"
  read_buffer_size = "64KiB"

[[processors.starlark]]
  order = 1
  source = '''
def apply(metric):
    for key in ["src", "dst", "protocol"]:
        if key in metric.fields:
            metric.tags[key] = str(metric.fields.pop(key))
    return metric
'''

[[processors.starlark]]
  order = 2
  script = "/etc/telegraf/app_classify.star"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "netflow_db"
  retention_policy = "raw_24h"
  write_consistency = "any"
  timeout = "10s"
  [outputs.influxdb.tagpass]
    src = ["192.168.52.*", "192.168.53.*", "192.168.54.*"]
